job_gcc_amd64:
  script:
    - ./autogen.sh
    - ./configure CXX="ccache g++" PYTHON=python3 --prefix=$PWD/install --with-python-module-path=$PWD/install/site-packages --enable-openmp
    - CCACHE_BASEDIR=$PWD make $MAKEOPTS
    - make install
    - export PYTHONPATH=$PWD/install/site-packages
    - cd doc; python3 /usr/bin/sphinx-build -b doctest . build *.rst demo/inference/inference.rst
  tags:
    - amd64

job_clang_amd64:
  script:
    - ./autogen.sh
    - ./configure CXX="ccache clang++" PYTHON=python3 --prefix=$PWD/install --with-python-module-path=$PWD/install/site-packages
    - CCACHE_BASEDIR=$PWD make $MAKEOPTS
    - make install
    - export PYTHONPATH=$PWD/install/site-packages
    - cd doc; python3 /usr/bin/sphinx-build -b doctest . build *.rst demo/inference/inference.rst
  tags:
    - amd64

job_gcc_py2_amd64:
  script:
    - ./autogen.sh
    - ./configure CXX="ccache g++" PYTHON=python2 --prefix=$PWD/install --with-python-module-path=$PWD/install/site-packages --enable-openmp
    - CCACHE_BASEDIR=$PWD make $MAKEOPTS
    - make install
    - export PYTHONPATH=$PWD/install/site-packages
    - cd doc; python2 /usr/bin/sphinx-build2 -b doctest . build *.rst demo/inference/inference.rst
  tags:
    - amd64

job_clang_py2_amd64:
  script:
    - ./autogen.sh
    - ./configure CXX="ccache clang++" PYTHON=python2 --prefix=$PWD/install --with-python-module-path=$PWD/install/site-packages
    - CCACHE_BASEDIR=$PWD make $MAKEOPTS
    - make install
    - export PYTHONPATH=$PWD/install/site-packages
    - cd doc; python2 /usr/bin/sphinx-build2 -b doctest . build *.rst demo/inference/inference.rst
  tags:
    - amd64

job_gcc_amd64_nosh:
  script:
    - ./autogen.sh
    - ./configure CXX="ccache g++" PYTHON=python3 --prefix=$PWD/install --with-python-module-path=$PWD/install/site-packages --enable-openmp --disable-sparsehash
    - CCACHE_BASEDIR=$PWD make $MAKEOPTS
    - make install
    - export PYTHONPATH=$PWD/install/site-packages
    - cd doc; python3 /usr/bin/sphinx-build -b doctest . build *.rst demo/inference/inference.rst
  tags:
    - amd64

job_clang_amd64_nosh:
  script:
    - ./autogen.sh
    - ./configure CXX="ccache clang++" PYTHON=python3 --prefix=$PWD/install --with-python-module-path=$PWD/install/site-packages --disable-sparsehash
    - CCACHE_BASEDIR=$PWD make $MAKEOPTS
    - make install
    - export PYTHONPATH=$PWD/install/site-packages
    - cd doc; python3 /usr/bin/sphinx-build -b doctest . build *.rst demo/inference/inference.rst
  tags:
    - amd64
